### ISSUE TITLE
Assets compilation not working

### ISSUE THREAD

**Issue by Hillsrion** [jackdbd/threejs-es6-webpack-starter#2]
file-loader dependency is missing in the package of the project, making the compilation fail when running yarn run server command.

![image](https://user-images.githubusercontent.com/12768773/31601494-563b7a9e-b25a-11e7-8742-db7fdb0f31bd.png)

**Comment by jackdbd** [comment]
Thanks for the heads-up @Hillsrion 

Hopefully everything works now

**Comment by Hillsrion** [comment]
You're welcome ! This is fixed
